services:
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
  server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=inklusiv_id
    depends_on:
      - db
    volumes:
      - ./server:/app
  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=inklusiv_id
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  client:
  db-data:
  server:
